version: "3.7"
services:
  app:
    container_name: app
    image: devops-sample-django-app
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8000/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_HOST=database
      - DJANGO_DB_NAME=app
      - DJANGO_DB_USER=worker
      - DJANGO_DB_PASS=worker
      - DJANGO_DB_PORT=5432
      - DJANGO_DEBUG=False
    depends_on:
      - database
    command: [ "bash", "-c", "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000" ]
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - django

  database:
    container_name: database
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 10s
      timeout: 20s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=worker
      - POSTGRES_PASSWORD=worker
    networks:
      - django

volumes:
  postgres:
    name: postgres

networks:
  django:
    name: django